base:
  config:
    oauth:
      hostname: localhost
      port: 9001
    nacos:
      hostname: 192.168.6.101
      port: 8848
    rabbitmq:
      hostname: 192.168.6.101
      port: 15672

spring:
  application:
    name: cloud-message
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 192.168.6.101
    port: 5672
    username: admin
    password: admin
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
dubbo:
  scan:
    base-packages: com.funtl.myshop.plus.cloud.producer
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token
      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize
    resource:
      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token

server:
  port: 10002

management:
  endpoints:
    web:
      exposure:
        include: "*"