base:
  config:
    rabbitmq:
      hostname: 192.168.6.101
      port: 15672
    nacos:
      hostname: 192.168.6.101
      port: 8848

spring:
  application:
    name: message-admin-login-log
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 192.168.6.101
    port: 5672
    username: admin
    password: admin
    virtual-host: /
dubbo:
  scan:
    base-packages: com.funtl.myshop.plus.message.consumer
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

server:
  port: 20001